### PR TITLE
changed update to install to test error

### PR DESCRIPTION
**Pull request by JoeCSykes**

### CODE REVIEW

**Comment by PietroConvalleAD** [comment]
What was causing the error? I think you can put poetry.lock back in the .gitignore and remove it from the git history

**Comment by PietroConvalleAD** [comment]
you haven't removed poetry.lock from git tho, `git rm --cached poetry.lock` then comment and push

**Comment by JoeCSykes** [comment]
so you do need the poetry lock file for the caching. See workflow error above

**Comment by PietroConvalleAD** [comment]
you should be able to cache the file tho

**Review by PietroConvalleAD — APPROVED** [review]

**Comment by JoeCSykes** [comment]
For future reference for this ticket, it was decided to keep a poetry lock file in the repo as this locks all devs into the same dependencies and also informs future devs of the latest dependencies this project is compatible with (see https://python-poetry.org/docs/basic-usage/). It was also tested that new dependencies are installed locally when a pull request is made with the lock file.

**Review by NogaAD — APPROVED** [review]

**Pull request merged**
